spring.application.name=civicpulsespringbootdemo
server.port=8083
spring.datasource.url=jdbc:mysql://localhost:3306/civicpulse
spring.datasource.username=root
spring.datasource.password=Chandana@#2106
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true